### ISSUE TITLE
Keep Getting This Line 7362 Crash While Moving The Menu Around My Screen While Generally Playing

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#342] opened 2022-04-07 19:27 UTC
![image](https://user-images.githubusercontent.com/24400879/162281269-51c6f7c4-8ce6-4e75-9657-68f5898caff8.png)

**Comment by cddjr** [comment] 2022-04-08 01:55
Duplicate of #335

**Closed** 2022-04-08 05:16 UTC
