### ISSUE TITLE
Scaling Error

### ISSUE THREAD

**Issue by OBNinjaa** [BitCrackers/AmongUsMenu#238] opened 2021-11-23 21:48 UTC
As soon as the dll is injected the resolution messes up.

![unknown](https://user-images.githubusercontent.com/64389208/143134573-bc32e33f-1fff-48ae-a116-cbe37cc2cccd.png)

**Comment by OBNinjaa** [comment] 2021-11-23 21:55
Tried rescaling in settings but doesn't fix the issue

**Comment by 4310V343k** [comment] 2021-11-24 06:50
Duplicate of #234

**Comment by v0idp** [comment] 2021-11-24 17:28
> As soon as the dll is injected the resolution messes up.
> 
> ![unknown](https://user-images.githubusercontent.com/64389208/143134573-bc32e33f-1fff-48ae-a116-cbe37cc2cccd.png)

please provide information about your monitor dpi, resolution and what mode you run the game in (fullscreen,windowed, etc) and also write down what you all tried to fix it yourself. for example change resolution or fullscreen/windowed

**Comment by 4310V343k** [comment] 2021-11-24 17:40
> this has nothing to do with that issue :P

Well, looked like it does ¯\\\_(ツ)_/¯

**Comment by kotae4** [comment] 2022-04-04 23:58
should be fixed in https://github.com/BitCrackers/AmongUsMenu/commit/230a6f32e4e04964ad7628838e606bf72ee71f25

**Closed by kotae4** 2022-04-04 23:58 UTC
Labels: question
