### ISSUE TITLE
My Game Keeps Crash Over and Over With the Menu. I Don't Know What's Different Than Last Night When It Was Working.

### ISSUE THREAD

**Issue by Bj007pro** [BitCrackers/AmongUsMenu#271] opened 2021-12-30 20:17 UTC
It was opening fine and not crashing last night, I put my PC to sleep mode like I usually do before I go to bed, and now today it keeps crashing over and over during startup.

Here's my AUM log:
[aum-log.txt](https://github.com/BitCrackers/AmongUsMenu/files/7794499/aum-log.txt)

**Comment by v0idp** [comment] 2021-12-30 21:39
duplicate of #269

**Closed by v0idp** 2021-12-30 21:39 UTC
